### ISSUE TITLE
Just installed it

### ISSUE THREAD

**Issue by pawelotto** [bdistin/fs-nextra#48]
And failed miserably: 
`
node_modules/fs-nextra/typings/index.d.ts:141:11 - error TS2304: Cannot find name 'readJsonAtomic'.

141  export { readJsonAtomic as writeJSONAtomic };
              ~~~~~~~~~~~~~~

node_modules/fs-nextra/typings/index.d.ts:141:11 - error TS2552: Cannot find name 'readJsonAtomic'. Did you mean 'writeJsonAtomic'?

141  export { readJsonAtomic as writeJSONAtomic };`

**Comment by kyranet** [comment]
I have made a PR to fix this, you can install it with any of the following commands in the meanwhile until the owner merges and publishes a patch version:

- `npm i bdistin/fs-nextra#c2e33edbc0fbe647f9b53a731cbbbc347d901836`
- `yarn add bdistin/fs-nextra#c2e33edbc0fbe647f9b53a731cbbbc347d901836`
